# Generated by Django 4.2.2 on 2023-06-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIKey', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('api_services', models.CharField(choices=[('Dowell Mail', 'Dowell Mail'), ('Dowell Scale', 'Dowell Scale')], max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credits', models.IntegerField(blank=True, default=50, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('workspace_id', models.CharField(max_length=255, null=True)),
                ('userDetails', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
                ('voucher_discount', models.IntegerField()),
            ],
        ),
    ]
