# Generated by Django 4.2.2 on 2023-07-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_service_id', models.CharField(max_length=255, unique=True)),
                ('api_service', models.CharField(max_length=255)),
                ('document_link', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('credits_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RedeemVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default=False, max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
                ('voucher_discount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APIKey', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('userDetails', models.JSONField(null=True)),
                ('api_services', models.JSONField(null=True)),
                ('is_redeemed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('APIKey', 'email')},
            },
        ),
    ]
