# Generated by Django 4.2.2 on 2023-07-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='total_credit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
