# Generated by Django 4.2.2 on 2023-07-05 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_apikey_total_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='total_credit',
            new_name='total_credits',
        ),
    ]
