# Generated by Django 4.2.2 on 2023-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_total_credit_apikey_total_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
    ]
