# Generated by Django 4.1.6 on 2023-07-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_apikey_api_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_service', models.CharField(max_length=255)),
                ('document_link', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
