# Generated by Django 4.2.2 on 2023-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_voucher_voucher_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
