# Generated by Django 4.2.2 on 2023-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_voucher_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
