# Generated by Django 4.2.2 on 2023-07-03 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='email',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='document',
            name='credits_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='api_services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.document'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
