# Generated by Django 4.1.6 on 2023-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='component',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='total_count',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
