# Generated by Django 4.2.2 on 2023-06-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_redeemvoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_services',
            field=models.CharField(choices=[('Living Lab scale', 'Living Lab scale'), ('Living Lab Chat', 'Living Lab Chat'), ('License compatibility', 'License compatibility'), ('UX Live', 'UX Live'), ('Statistical distributions from bigdata', 'Statistical distributions from bigdata'), ('Dowell Payments', 'Dowell Payments'), ('QR code', 'QR code'), ('Dowell Email', 'Dowell Email'), ('Sampling from big data', 'Sampling from big data'), ('Permutations', 'Permutations'), ('Shuffling of Big data', 'Shuffling of Big data'), ('Wifi QR Code', 'Wifi QR Code'), ('Living lab Maps', 'Living lab Maps'), ('Secure repositories', 'Secure repositories'), ('Geometrical layout of Big Data', 'Geometrical layout of Big Data'), ('Central tendencies of Big data distributions', 'Central tendencies of Big data distributions')], max_length=255, unique=True),
        ),
    ]
