# Generated by Django 4.2.2 on 2023-07-03 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_apikey_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='userId',
            new_name='email',
        ),
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('APIKey', 'email')},
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='username',
        ),
    ]
