# Generated by Django 4.1.6 on 2023-07-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_apikey_component_component_total_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('components', models.JSONField(blank=True, null=True)),
                ('credit_count', models.CharField(blank=True, max_length=225)),
                ('total_count', models.CharField(blank=True, max_length=225)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
            ],
        ),
    ]
