# Generated by Django 4.1.6 on 2023-07-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='credit_count',
            field=models.IntegerField(),
        ),
    ]
