# Generated by Django 4.1.6 on 2023-07-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_apikey_api_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='userId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
