# Generated by Django 4.1.6 on 2023-07-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_component_credit_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='total_count',
            field=models.IntegerField(blank=True, max_length=225),
        ),
    ]
