# Generated by Django 4.2.2 on 2023-06-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_apikey_api_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeemvoucher',
            name='voucher_code',
            field=models.CharField(max_length=255),
        ),
    ]
