# Generated by Django 4.1.6 on 2023-07-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_component_total_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='credit_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='total_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
