# Generated by Django 4.2.2 on 2023-06-26 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_apikey_api_services_alter_apikey_workspace_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apikey',
            unique_together={('workspace_id', 'api_services')},
        ),
    ]
