# Generated by Django 4.2.2 on 2023-07-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_apikey_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, unique=True)),
                ('libraries', models.JSONField(blank=True, null=True)),
                ('credit_count', models.CharField(blank=True, max_length=225)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='library',
            name='library_id',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
