# Generated by Django 4.1.6 on 2023-07-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_library_library_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='component',
            new_name='Component',
        ),
        migrations.AddField(
            model_name='apikey',
            name='Product',
            field=models.JSONField(null=True),
        ),
    ]
