# Generated by Django 4.2.2 on 2023-06-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_apikey_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='workspace_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
