# Generated by Django 4.2.2 on 2023-07-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_component_apikey_component_apikey_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flutterflow',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('libraries', models.JSONField(blank=True, null=True)),
                ('total_credit_count', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
