# Generated by Django 4.1.6 on 2023-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_flutterflow_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='flutterflow',
            name='name',
            field=models.CharField(default='test', max_length=225, unique=True),
        ),
    ]
