# Generated by Django 4.1.6 on 2023-07-16 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_flutterflow_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='total_count',
            new_name='total_credit_count',
        ),
    ]
