# Generated by Django 4.2.2 on 2023-07-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_total_count_library_total_credit_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flutterflow_component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Flutterflow_component_id', models.CharField(max_length=225, unique=True)),
                ('api_service', models.JSONField(blank=True, null=True)),
                ('flutterflow_link', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_id', models.CharField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('api_service', models.JSONField(blank=True, null=True)),
                ('plugin_link', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Flutterflow',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='apiservices',
            new_name='api_service',
        ),
        migrations.RenameField(
            model_name='component',
            old_name='credit_count',
            new_name='credits_count',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='components',
            new_name='api_service',
        ),
        migrations.RenameField(
            model_name='library',
            old_name='total_credit_count',
            new_name='credits_count',
        ),
        migrations.RemoveField(
            model_name='component',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='library',
            name='credit_count',
        ),
        migrations.AddField(
            model_name='component',
            name='Component_id',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='component_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='library_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_id',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
