# Generated by Django 4.2.2 on 2023-07-17 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_flutterflow_component_plugin_delete_flutterflow_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flutterflow_component',
            old_name='flutterflow_link',
            new_name='flutter_flow_component_link',
        ),
        migrations.AddField(
            model_name='flutterflow_component',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
