# Generated by Django 4.2.2 on 2023-07-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_flutterflow_link_flutterflow_component_flutter_flow_component_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=225, unique=True)),
                ('api_service', models.JSONField(blank=True, null=True)),
                ('plugin_link', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
