# Generated by Django 4.2.2 on 2023-07-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_plugin_link_product_product_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
