# Generated by Django 4.1.6 on 2023-07-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='credits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
