# Generated by Django 4.1.6 on 2023-07-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_apikey_credits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plugin',
        ),
        migrations.AddField(
            model_name='apikey',
            name='flutter_flow',
            field=models.JSONField(null=True),
        ),
    ]
