# Generated by Django 4.1.6 on 2023-07-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_apikey_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='flutter_flow',
            new_name='flutterflow',
        ),
    ]
