# Generated by Django 4.1.6 on 2023-07-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_flutter_flow_apikey_flutterflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='library_id',
            new_name='libraryidd',
        ),
    ]
