# Generated by Django 4.1.6 on 2023-07-19 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_library_id_library_libraryidd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='libraryidd',
            new_name='libraryid',
        ),
    ]
