# Generated by Django 4.2.2 on 2023-07-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_service_id', models.CharField(max_length=255, unique=True)),
                ('name_service', models.CharField(max_length=255)),
                ('document_link', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MODULE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(choices=[('WordPress Plugin', 'WordPress Plugin'), ('React Component', 'React Component'), ('Flutter Component', 'Flutter Component'), ('Library', 'Library')], max_length=50)),
                ('module_id', models.CharField(max_length=255, unique=True)),
                ('name_module', models.CharField(max_length=255)),
                ('document_link', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField()),
                ('api_service_ids', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=225, unique=True)),
                ('product_name', models.CharField(max_length=225, unique=True)),
                ('product_link', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=True)),
                ('credits_count', models.IntegerField(blank=True, null=True)),
                ('types', models.JSONField(null=True)),
            ],
        ),
    ]
