# Generated by Django 4.2.2 on 2023-07-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default=False, max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, unique=True)),
                ('voucher_code', models.CharField(max_length=255, unique=True)),
                ('voucher_discount', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
